### ISSUE TITLE
Adjustable Speed Test

### ISSUE THREAD

**Issue by mrdeadlocked** [danopstech/starlink#2]
What would be the easiest way to adjust the speed test frequency?

**Comment by dwillcocks** [comment]
You need to adjust how often Prometheus scrapes the speedtest_exporter. This setting is in: `config/prometheus/prometheus.yml`

Change the "scrape_interval" to your desired setting.
```
...
  - job_name: 'speedtest'
    scrape_interval: 60m    <-------- HERE
    scrape_timeout: 70s
    static_configs:
      - targets: [ 'speedtest_exporter:9090' ]
...
```
